root: true
parser: babel-eslint
extends: airbnb
plugins:
  - react
  - import
  - async-await
  - jest
env:
  browser: true
  node: true
  jest: true
rules:
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  react/jsx-filename-extension: 0
  react/jsx-props-no-spreading: 0
  no-underscore-dangle: 0
  no-return-await: 0
  arrow-parens: 0
  comma-dangle: 0
  consistent-return: 0
  jsx-quotes: 0
  no-use-before-define: 0
  operator-linebreak: 0
  no-console: 0
  max-len: ['error', 100]
